// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRecordViewer.DL;

namespace StudentRecordViewer.DL.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentRecordViewer.DL.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCreditsId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentCreditsId")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentRecordViewer.DL.StudentCredits", b =>
                {
                    b.Property<int>("StudentCreditsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Year1Credits")
                        .HasColumnType("int");

                    b.Property<int>("Year2Credits")
                        .HasColumnType("int");

                    b.Property<int>("Year3Credits")
                        .HasColumnType("int");

                    b.Property<int>("Year4Credits")
                        .HasColumnType("int");

                    b.Property<int>("Year5Credits")
                        .HasColumnType("int");

                    b.HasKey("StudentCreditsId");

                    b.ToTable("StudentCredits");
                });

            modelBuilder.Entity("StudentRecordViewer.DL.Student", b =>
                {
                    b.HasOne("StudentRecordViewer.DL.StudentCredits", "StudentCredits")
                        .WithOne("Student")
                        .HasForeignKey("StudentRecordViewer.DL.Student", "StudentCreditsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentCredits");
                });

            modelBuilder.Entity("StudentRecordViewer.DL.StudentCredits", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
